#!/usr/bin/env php
<?php

declare(strict_types=1);

(static function (): void {
    if (file_exists($autoload = __DIR__.'/../../autoload.php')) {
        // Is installed via Composer
        include_once $autoload;

        return;
    }

    if (file_exists($autoload = __DIR__.'/vendor/autoload.php')) {
        // Is installed locally
        include_once $autoload;

        return;
    }

    throw new RuntimeException('Unable to find the Composer autoloader.');
})();

use Cx\Commands;
use Symfony\Component\Console\Application;

$application = new Application();

$application->addCommands([
    new Commands\AffectedCommand(),
    new Commands\GraphCommand(),
    new Commands\RunManyCommand(),
]);

$application->run();
