#!/usr/bin/env php
<?php

$autoloader = require(__DIR__ . '/vendor/autoload.php');

use Cx\Commands;
use Symfony\Component\Console\Application;

$application = new Application();

$application->addCommands([
    new Commands\AffectedCommand(),
    new Commands\GraphCommand(),
    new Commands\RunManyCommand(),
]);

$application->run();
